# docker-compose.yml
version: '3.4'
services:
  nginx:
    image: nginx:1.1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
      - 8843:443
    volumes:
      - ./log/nginx-log:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
